### ISSUE TITLE
AWS Support Limits API is deprecated

### ISSUE THREAD

**Issue by RmMsr** [danielfm/aws-limits-exporter#3]
Hi there,

his is rather an Info than an issue. I hope it helps anyway.

We got the following error in all aws_limits_exporter pods:

>  Cannot retrieve Trusted Advisor check results data: InvalidParameterValueException: Unknown ID: eW7HH0l7J9

The reason for this is that AWS had disabled this specific Check of the TrustedAdvisor for several hours. It is deprecated. According to the AWS support they have re-enabe it now, but cannot tell for how long it will stay up. In general all users are advised to use a different source for monitoring Service Limits.

I had a look at the Quota-Dashboard. This seems to be the way to go.

BTW: Thanks a lot for the exporter. It's is and was very useful!

**Comment by danielfm** [comment]
Is this the dashboard you're referring to?

https://aws.amazon.com/blogs/mt/introducing-service-quotas-view-and-manage-your-quotas-for-aws-services-from-one-central-location/

I'm no longer working with AWS, so I'm not able to change the code to adapt to the new API. I'll be happy to accept any PRs in that area, if anyone's interested to help.

**Comment by RmMsr** [comment]
Exactly. And it of course comes with an API. But I haven't found a way to get the current absolute quota / limit similar to the TrustedAdvisor ServiceLimits. I might as well just have overlooked it. 

The TrustedAdvisor API also reports highly utilized services (> 80%) in the form of an alert. That is much less useful than the actual absolute numbers over time. Until now I see no real alternative to the Support API ServiceLimits for the aws_limits_exporter.

**Comment by danielfm** [comment]
Closed by #4
