### ISSUE TITLE
Add region argument

### ISSUE THREAD

**Issue by colinliddlemyob** [danielfm/aws-limits-exporter#6]
Even though we have to use the us-east-1 region to actually get the metrics, it would be useful if we can specify the region at least to reduce the number of metrics gathered and reported if we only care about one region

**Comment by colinliddlemyob** [comment]
I'm happy to make this change if you think it's a good idea

**Comment by danielfm** [comment]
Sounds like a good idea, as long as we keep the default behavior as is!

Em seg, 24 de fev de 2020 02:14, Colin Liddle <notifications@github.com>
escreveu:

**Comment by colinliddlemyob** [comment]
Yep, I'll just add an optional argument, if it's not supplied it will behave as it does now
